### ISSUE TITLE
Please provide file hash along with the download link

### ISSUE THREAD

**Issue by auooo** [scriptingxss/EmbedOS#3]
Just want to ensure the file downloaded is the correct one.

**Comment by scriptingxss** [comment]
Hi, the direct link with the updated VM (2020.2) can be found on google drive @ https://drive.google.com/file/d/1t53Q1LaKxd7WeXiw21syhbGbvZFkLzWh/view?usp=sharing

Ive added the hash checksums for SHA256 and SHA512 in the readme. 
$ shasum -a 256 EmbedOS_2020.2-disk1.vmdk
f95f8c72e6dc1a57369a37ed4699c50a6ce7c0f7d86b23715a031151e09c4635  EmbedOS_2020.2-disk1.vmdk
$ shasum -a 512 EmbedOS_2020.2-disk1.vmdk
6db0142ddcd63e8096f3a97ca5d964862ea1d80aa71f07095fe5da0ced075d1446998fc13f9062cb22145589129a2ee2849f3f55e7c4b2bbcd0725afba8e3b55  EmbedOS_2020.2-disk1.vmdk

**Comment by auooo** [comment]
Thanks:)
